## Essential Tools
brew "stow"
brew "mise"
brew "tree"
brew "tmux"
brew "neovim"
brew "prettierd"
brew "stylua"
brew "yt-dlp"
brew "ffmpeg"
brew "libyaml"
brew "the_silver_searcher"
brew "ripgrep"
brew "wget"
brew "jq"
brew "git-delta"

## Editors
cask "ghostty"
cask "gitkraken"
# cask "visual-studio-code"

## Browsers
cask "mullvad-vpn"
cask "mullvad-browser"
cask "eloston-chromium"
# cask "firefox"
# cask "google-chrome"

## Development Tools
cask "rancher"
brew "kubectx"
brew "kube-ps1"

## Productivity Applications
cask "obsidian"
cask "meetingbar"

## Utility Applications
cask "swish"
cask "raycast"
cask "hiddenbar"
cask "1password"
# cask "discord"
# cask "anydesk"



