# prompt
format = """
$time$username$hostname$directory$git_branch$git_status$kubernetes$cmd_duration
$character"""

# username - only shown over SSH
[username]
detect_env_vars = ["SSH_CONNECTION"]
format = "[$user]($style)@"
style_user = "bold yellow"
style_root = "bold red"

# hostname - only shown over SSH
[hostname]
ssh_only = true
format = "[$hostname]($style) in "
style = "bold yellow"

# time
[time]
disabled = false
format = "[∴]($style) "
style = "green"

# directory
[directory]
truncate_to_repo = true
truncation_symbol = ""

# git
[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

# kubernetes
[kubernetes]
disabled = false
format = "at [$symbol$context( \\($namespace\\))]($style) "
style = "red"

[kubernetes.context_aliases]

# execution time
[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

# character
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# disabled sections
[docker_context]
disabled = true

[gcloud]
disabled = true
